name: Terraform
on:
- push

jobs:
  checkfmt:
    name: Format
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 1.2.6

    - name: Check format
      run: make checkfmt

  validate:
    name: Validate
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 1.2.6

    - name: Validate
      run: make validate

  docs:
    name: Docs
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docs
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        git-push: true
        output-file: README.md
        output-method: inject
        working-dir: .

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 1.2.6

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.38.1

    - name: Lint
      run: make lint
